### PR TITLE
Pass in 'Connect to GitHub' command id to DeploymentsTreeItem

### PR DESCRIPTION
**Pull request by nturinski**
Depends on Microsoft/vscode-azuretools#349

### CODE REVIEW

**Comment by EricJizbaMSFT** [comment]
FYI - remember you need to update the package-lock every time you bump a package from now on

**Comment by nturinski** [comment]
... ruh roh.  Right, so that's just doing an `npm install` right?

**Comment by EricJizbaMSFT** [comment]
Yep - but of course `npm install` won't work until after the shared package is published

**Comment by nturinski** [comment]
Naturally 😎

**Pull request merged**
