### PR TITLE
Remove Csharp tests 

### PR DESCRIPTION
**Pull request by motm32**
Doing this since our CodeQL snapshots are failing for csharp and we could either remove the files, add a build task, or create a seperate non-production repo in order to be compliant. After discussion we decided to just remove the tests.

### CODE REVIEW

**Comment by alexweininger** [comment]
Is it possible to verify that this passes CodeQL before merging? If you need to, you can manually run the 1ES pipeline

**Comment by motm32** [comment]
Yup I can try doing that!

**Comment by motm32** [comment]
Manually ran a build on this branch and the CodeQL detected languages are now only Javascript and Python so no more warnings from CodeQL about csharp.

**Comment by nturinski** [comment]
lmao, hooray for compliance actually reducing our test coverage. . . 🎉

**Pull request merged**
