### PR TITLE
Working with my front end developers who would like to move off of full visual studio, they would really appreciate a way to ship code from VSC 

### PR DESCRIPTION
**Pull request by beaudryj**
By Design I need to be able to target and deploy to windows based azure web apps, and modifying this out seemed to work fine.

### CODE REVIEW

**Comment by brentmannarino** [comment]
This is super helpful to be able to deploy from VSCode to my windows app

**Comment by beaudryj** [comment]
https://github.com/Microsoft/vscode-azureappservice/issues/67

**Comment by EricJizbaMSFT** [comment]
@beaudryj Thanks for the contribution! As a workaround until this gets released, your windows web apps should still be listed in the App Service Explorer. You should be able to right click on a web app and deploy from there:
screen shot 2017-11-17 at 10 23 35 am

**Comment by beaudryj** [comment]
sadly that grabs the whole workspace, rather than say my "Dist" directory generated by my NG Build

**Pull request merged**
