### PR TITLE
Change folder icons and add file icons

### LINKED ISSUE #487: No icons display for the sub-nodes under 'Files/Log Files'
Repro Steps:
1. Go to Subscription -> Select one web app.
2. Expand 'Files/Log Files' under the selected app -> Check the sub-nodes.

Expected:
Dispaly icons for the sub-nodes under 'Files/Log Files'.

Actual:
No icons display for the sub-nodes under 'Files/Log Files'.
compare

### PR DESCRIPTION
**Pull request by nturinski**
The new folder icons are in color and pop a bit more.
Added a generic file icon to all of the files.

Fixes #487

### CODE REVIEW

**Comment by EricJizbaMSFT** [comment]
screenshots?

**Comment by nturinski** [comment]
files_folder_dark
files_folder_light

**Comment by nturinski** [comment]
Got your instructions-- will update soon.

The subfolders don't have an icon because I'm imitating the VS Code File Explorer.

image

I remember I tried adding a folder to each subfolder and it looked very cluttered.

**Comment by nturinski** [comment]
Updated icons. Looks much better.  THANK YOU.

files_folder_dark

files_folder_light

**Pull request merged**
