### PR TITLE
Merge unified into main

### PR DESCRIPTION
**Pull request by alexweininger**

### CODE REVIEW

**Review by bwateratmsft — DISMISSED** [review]

**Comment by alexweininger** [comment]
Anyone know how to fix the CI for this? It's giving some weird npm error.

**Comment by bwateratmsft** [comment]
> Anyone know how to fix the CI for this? It's giving some weird npm error.

Version conflicts maybe? Are these using the 0.3.0 utils/azureutils?

**Comment by alexweininger** [comment]
> > Anyone know how to fix the CI for this? It's giving some weird npm error.
> 
> Version conflicts maybe? Are these using the 0.3.0 utils/azureutils?

The error is `npm ERR! @azure/arm-subscriptions not accessible from @microsoft/vscode-azext-dev`

Others have fixed it by regenerating their package-lock. I tried and it didn't work. Someone also mentioned upgrading/downgrading npm could solve it. 
https://stackoverflow.com/questions/55014020/running-npm-ci-returns-pkg-dir-not-accessible-from-find-cache-dir

**Comment by nturinski** [comment]
How did you end up fixing this?

**Review by nturinski — APPROVED** [review]

**Comment by alexweininger** [comment]
> How did you end up fixing this?

Deleted package-lock and node_modules.

**Pull request merged**
