### PR TITLE
Refactor remote debugging commands into common library

### PR DESCRIPTION
**Pull request by mrcrane**
Pull out the common remote debugging code into the vscode-azureappservice library.

This change requires the changes in Microsoft/vscode-azuretools#522 (see that PR for more details about what is being changed here)

Also has some changes to get rid of the "Stop Remote Debugging" command and clean up the context menu grouping remote debugging and SSH commands: 

image

### CODE REVIEW

**Comment by EricJizbaMSFT** [comment]
ping @nturinski @mrcrane what's the status of this PR?

**Comment by EricJizbaMSFT** [comment]
Omg both of you 😂😂😂

Screen Shot 2019-07-24 at 2 12 53 PM

**Comment by mrcrane** [comment]
Sorry I got pulled away to work on other things and left this hanging. Clearly restarting the build isn't enough to get this passing 😄 I'll fix it up and send an update soon.

**Comment by mrcrane** [comment]
I rebased onto master and everything builds and tests properly. I did some manual testing as a sanity check and it looks good. All it actually needed was for the package.json to reference a newer 'vscode-azureappservice' that contains the new changes from microsoft/vscode-azuretools#522

@nturinski Feel free to take a look now. I updated the description to have a little more context. Definitely let me know if the context menu looks good or if I should reorder anything.

**Pull request merged**
